name = "SSI"
uuid = "c2ec4192-8352-41d5-83dd-d207a473ad22"
repo = "."

[packages]
094bb4ec-04e4-4f11-bf12-e5749f7dd418 = { name = "Influenza", path = "I/Influenza" }
75be95bb-60e3-4423-b8b7-0f2a09593d53 = { name = "InfluenzaCore", path = "I/InfluenzaCore" }
7ee4cdc4-8348-4b3e-96a1-d8fae3cd589d = { name = "NCBIInfluenzaData", path = "N/NCBIInfluenzaData" }
b5cebcd4-064d-411e-b7d2-9c254a506bcf = { name = "VetLIMS", path = "V/VetLIMS" }
f2dc44fa-c02b-42d6-8c22-04adf9d07357 = { name = "KMATools", path = "K/KMATools" }
